Cwyan2483/astrologica

- index.html
Moved the css folder into assets and slightly edited h1 tag
> housekeeping

- assets/js/script.js
- index.html
> added js folder and js pseudocode

- index.html
Added more specific html tags and gave them ids based off of the pseudocode. Worked on page structuring.
> Basic html

- assets/js/script.js
- index.html
added info function and added some ids to html.
> added info function

- assets/js/script.js
- index.html
corrected some mistakes in html and js.
> Info function

- assets/js/script.js
added js code to obtain data that will need to be edited after the API call function is merged
> added code to create html elements from api info

- assets/js/script.js
changed from City.html to city.html
> from City.html to city.html

- index.html
> Modal function

- assets/js/script.js
- index.html
Fixed the issue where the cards were not displaying the proper information. The sun and moon events are now split.
> fixed the card names

- assets/js/script.js
- index.html
Wrote a function to display the picture of the day in the header
> added picture of the day API

- assets/js/script.js
- index.html
> added the load message

- css/app.css
- index.html
Added placeholder code for images accompanying the card content
> added divs for image placement

- assets/js/script.js
got rid of the previous loading message
> cleared the previous loading message

- assets/js/script.js
- index.html
> please check application for local storage

- css/app.css
Added shadow to header text allowing it to be more visible
> Header text changes

- assets/js/script.js
- index.html
Fixes the user input so that the first letter of the city is capitalized
> added function to fix input display

- assets/js/script.js
- css/app.css
- index.html
added buttons to save searches and view most recent searches
> Button branch

- assets/js/script.js
Fixed the city display so that they dont add to each other with multiple submits
> fixed multiple click bug

- assets/js/script.js
- css/app.css
- index.html
created a spinner but it appears before inputting the city name. I am working on clearing it for my next commit.
> added a spinner

- assets/js/script.js
Gets the API to work and get data, but need to work on how to use the data.
> added implementation of planetary API

- assets/js/script.js
- index.html
saved and view searches button working. just little bug with saved searches button still working on.
> created saved search and view seraches button

- assets/js/script.js
- css/app.css
- index.html
-clear search button clears local storage data and removes the generated buttons
-fixed html display so that our button tags are in numerical order. Updated any dom elements that would have been affected by the changes.
-disables the save search option when the data is loading, and makes it clickable when the data is displayed.
> Save planet func
